name: Vite Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress install
      #  run: npm install
      # - name: Cypress run
      #  uses: cypress-io/github-action@v2
        with:
        #  config-file: cypress.config.ts
        #  install: false
           ci: npm ci
           build: npm run build
           start: npm start
           run: npm run dev
           test: npm run test --coverage
